# source: https://github.com/JamesTurland/JimsGarage/blob/main/IT-Tools/docker-compose.yaml

version: "3.9"
services:
    it-tools:
        image: "corentinth/it-tools:latest"
        restart: unless-stopped
        container_name: ittools
        networks:
          - proxy
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=proxy"
          - "traefik.http.routers.ittools-secure.entrypoints=https"
          - "traefik.http.routers.ittools-secure.rule=Host(`ittools.server.home`)"
          - "traefik.http.routers.ittools-secure.tls=true"
          - "traefik.http.routers.ittools-secure.service=ittools"
          - "traefik.http.services.ittools.loadbalancer.server.port=80"

networks:
  proxy:
    external: true 
