# source: https://github.com/JamesTurland/JimsGarage/blob/main/Portainer/docker-compose.yaml

version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
#      - 8000:8000
      - 9000:9000 # uses http since traefik terminates https
    volumes:
      - portainer_data:/data
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    restart: unless-stopped
#    privileged: true
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.rule=Host(`portainer.server.home`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
volumes:
  portainer_data:

networks:
  proxy:
    external: true
