- name: Home
  hide-desktop-navigation: true
  columns:
    - size: full
      widgets:
        - type: server-stats
          servers:
            - type: local
              name: nixos-server
              hide-mountpoints-by-default: true
              mountpoints:
                "/":
                  hide: false
                  name: root
                "/mnt/nasdata":
                  hide: false
                  name: nas
        - type: bookmarks
          groups:
            - title: Infra
              color: 10 70 50
              links:
                - title: Traefik
                  url: https://traefik-hl.timoster.dev/
                - title: Portainer
                  url: https://portainer-hl.timoster.dev/
            - title: Tools
              color: 200 50 50
              links:
                - title: IT-Tools
                  url: https://ittools-hl.timoster.dev/
