version: "3.3"
services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./config:/app/config
      - /mnt/nasdata:/mnt/nasdata:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.glance.entrypoints=https"
      - "traefik.http.routers.glance.rule=Host(`start.server.home`)"
      - "traefik.http.routers.glance.tls=true"
      - "traefik.http.routers.glance.service=glance"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
